export type ExportWorkRow = {
  "作品ID externalId": string;
  "原书名 title": string;
  "作者 author": string;
  "品类 category": string;
  "当前简介 description": string;
  "当前播放量 currentPlays": number | string;
  "当前点击率 currentCtr": string;
  "当前完播率 currentFinish": string;
  "封面文件名 coverFileName": string;
  "封面地址 remoteUrl": string;
  "识别匹配作品名": string;
  "识别匹配作者": string;
  "识别置信度": string;
  "识别理由": string;
  "识别风险": string;
  "是否人工确认": string;
  "人工确认书名": string;
  "人工确认作者": string;
  "作品评级 rating": string;
  "评级分数 score": number | string;
  "评级置信度 confidence": string;
  "评级理由 reasons": string;
  "风险点 risks": string;
  "证据 evidence": string;
  "是否建议多书名运营 renameSuggestion": string;
  "多书名建议理由 renameReason": string;
  "生成 provider": string;
  "生成策略 strategy": string;
  "策略说明 strategyReason": string;
  "是否建议多书名方案": string;
  "新书名1": string;
  "新书名1理由": string;
  "新书名2": string;
  "新书名2理由": string;
  "新书名3": string;
  "新书名3理由": string;
  "新书名4": string;
  "新书名4理由": string;
  "新书名5": string;
  "新书名5理由": string;
  "新版简介": string;
  "简介优化理由": string;
  "封面Prompt": string;
  "封面评分 score": number | string;
  "封面评级 rating": string;
  "封面优点 strengths": string;
  "封面问题 weaknesses": string;
  "封面处理策略 strategy": string;
  "封面处理理由 reason": string;
  "封面是否人工确认 confirmed": string;
  "封面人工确认策略 confirmedStrategy": string;
  "封面人工备注 note": string;
  "新版封面1:1地址": string;
  "新版封面3:4地址": string;
  "重绘封面 provider": string;
  "重绘封面状态": string;
  "重绘封面 prompt": string;
  "重绘结果摘要": string;
  "重绘1:1是否已生成": string;
  "重绘3:4是否已生成": string;
  "重绘封面1:1地址": string;
  "重绘封面3:4地址": string;
  "导出时间 exportedAt": string;
};

export type ExportWorkbookPayload = {
  rows: ExportWorkRow[];
  fileName: string;
};
